apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-readiness-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container-readiness-app
  template:
    metadata:
      labels:
        app: container-readiness-app
    spec:
      containers:
      - name: container-readiness-app
        image: quay.io/w_schipp/kcrap:latest
        ports:
        - containerPort: 5000
        env:
        - name: SECRET
          value: T7vQKTUk4SCPHyxNBQPjmktJAHW0zUGHmxmLLiss
        - name: LLM_KEY
          value: none
        - name: S3_URL
          value: 10.97.111.36:9000
        - name: KEY
          value: UMBCY9pH5Cra5YNDHOgR
        - name: LLAMACPP_URL
          value: http://10.110.9.236/completion 
        - name: RUN_MODE
          value: llamacpp     
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        imagePullPolicy: Always