apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-readiness-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container-readiness-app
  template:
    metadata:
      labels:
        app: container-readiness-app
    spec:
      containers:
      - name: container-readiness-app
        image: ghcr.io/willschipp/crap:latest
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: my-llm-secret 
        env:
        - name: DYNACONF_S3_URL
          value: "10.108.36.177:9000"
        - name: DYNACONF_S3_ACCESS_KEY_ID
          value: "dcbHKrI1cXjjULOh8Yeh"  
        - name: DYNACONF_S3_secret_access_key
          value: "TZqZxFAylocAWcKEEgd7Lzf8YQqRWMxFqNwb7GnS"                            
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        imagePullPolicy: Always        