apiVersion: v1
kind: Service
metadata:
  name: container-readiness-app-service
spec:
  selector:
    app: container-readiness-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer