apiVersion: apps/v1
kind: Deployment
metadata:
  name: codellama-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codellama-app
  template:
    metadata:
      labels:
        app: codellama-app
    spec:
      containers:
      - name: codellama-app
        image: quay.io/w_schipp/model_work:latest
        ports:
        - containerPort: 8080