apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    openshift.io/display-name: LlamaCPP
  name: llamacpp
  labels:
    name: llamacpp
spec:
  containers:
    - image: quay.io/w_schipp/model_work:latest
      env:
        - name: MODEL_PATH
          value: /mnt/models
        - name: HOST
          value: 0.0.0.0
      name: kserve-container
      ports:
        - containerPort: 8080
          name: http1
          protocol: TCP
          hostPort: 8001
      securityContext:
        runAsNonRoot: false
  multiModel: false
  supportedModelFormats:
    - name: custom-format
      version: "1"
      autoSelect: true