apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio-server
  template:
    metadata:
      labels:
        app: minio-server
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio
        ports:
        - containerPort: 9000
        - containerPort: 9001
        args:
        - server
        - /data
        - --console-address
        - ":9001"
        imagePullPolicy: Always          