apiVersion: v1
kind: Service
metadata:
  name: minio-console
  labels:
    app: minio
spec:
  type: LoadBalancer
  ports:
    - name: console-port
      port: 9001
      targetPort: 9001
      protocol: TCP
    - name: service-port
      port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: minio-server