name: Build and Push Docker Image to ghcr

on:
  workflow_dispatch:
      
jobs:
  
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}        

      - name: 'Build Inventory Image'
        working-directory: ./app
        run: |
          docker build . --tag ghcr.io/willschipp/crap:latest
          docker push ghcr.io/willschipp/crap:latest