name: Build and Push Docker Image to ghcr

on:
  workflow_dispatch:
      
jobs:
  
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 'Build Inventory Image'
        run: |
          docker build . --tag ghcr.io/willschipp/crap:latest
          docker push ghcr.io/willschipp/crap:latest